
-- Create status lookup table
CREATE TABLE customer_status (
    id TINYINT PRIMARY KEY,
    status_name VARCHAR(20) UNIQUE NOT NULL
);

-- Insert status values
INSERT INTO customer_status (id, status_name) VALUES
(1, 'Active'),
(2, 'Inactive'),
(3, 'Cancelled');

-- Create customers table with normalized status
CREATE TABLE customers (
    id INT PRIMARY KEY AUTO_INCREMENT,
    status_id TINYINT NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    email_address VARCHAR(255) NOT NULL UNIQUE,
    address_line_one VARCHAR(255) NOT NULL,
    address_line_two VARCHAR(255),
    city VARCHAR(100) NOT NULL,
    state CHAR(2) NOT NULL,
    zip VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (status_id) REFERENCES customer_status(id)
);


-- Insert customer data
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'Roger', 'Flack', '862-287-1718', 'Roger_Flack96@1kmd3.space', '159 Beaconsfield Grove', NULL, 'Norfolk', 'So', '60647');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'Andie', 'Dann', '567-165-0376', 'Andie_Dann1452@fhuux.us', '1583 Blandford Grove', NULL, 'Pittsburgh', 'No', '60804');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (3, 'Matt', 'Yarlett', '437-855-1523', 'Matt_Yarlett6948@nmz0p.website', '2021 Maple Road', NULL, 'Henderson', 'Il', '60617');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'Michelle', 'Young', '533-402-0306', 'Michelle_Young2884@ptr6k.store', '960 Sheffield Lane', NULL, 'Omaha', 'Te', '60647');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'Kimberly', 'Forester', '757-013-5406', 'Kimberly_Forester3629@3wbkp.space', '3702 Bazely Walk', NULL, 'Escondido', 'Co', '60804');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (3, 'Kurt', 'Brown', '651-700-5244', 'Kurt_Brown2360@gnjps.host', '5240 Walnut Road', NULL, 'Innsbruck', 'Mo', '60617');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'Paige', 'Uddin', '260-238-0568', 'Paige_Uddin7362@ohqqh.property', '6654 Bloomsbury Street', NULL, 'Paris', 'Ne', '60634');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'Rachael', 'Simpson', '511-781-2368', 'Rachael_Simpson9046@v1wn5.info', '1288 Virginia Street', NULL, 'Berna', 'De', '60608');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (3, 'Lindsay', 'Rogan', '715-276-1628', 'Lindsay_Rogan6000@yahoo.auction', '890 Camelot Crossroad', NULL, 'Orlando', 'Il', '60123');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'Karla', 'Radley', '816-4580521', 'Karla_Radley3763@cke3u.edu', '1302 Berry Avenue', NULL, 'San Francisco', 'Il', '60625');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'Lexi', 'Kirby', '368-273-6178', 'Lexi_Kirby1398@ckzyi.audio', '3859 Empress Walk', NULL, 'Lakewood', 'Il', '60647');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (3, 'Carl', 'Richards', '683-801-7142', 'Carl_Richards9052@1kmd3.info', '2877 Clissold Drive', NULL, 'Phoenix', 'Mi', '60804');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'benny', 'mackenzie', '3610780357', 'Benny_Mackenzie8085@1wa8o.info', '8899 Durweston Lane', NULL, 'Lyon', 'Il', '60617');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'Camellia', 'Jordan', '357-614-6601', 'Camellia_Jordan2083@cke3u.tech', '4445 Calvin Avenue', NULL, 'Prague', 'Oh', '60645');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (3, 'Mackenzie', 'Lane', '528-840-2053', 'Mackenzie_Lane5573@kyb7t.business', '6493 Collingwood Lane', NULL, 'Los Angeles', 'Ne', '60608');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'Zoe', 'Asher', '184-604-7743', 'Zoe_Asher9937@ckzyi.online', '6654 Tiptree Street', NULL, 'Paris', 'Il', '60586');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'Johnny', 'Notman', '232-032-4273', 'Johnny_Notman5397@yvu30.host', '3294 Dyott Walk', NULL, 'Detroit', 'Il', '60625');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (3, 'Ethan', 'Cunningham', '258-434-7323', 'Ethan_Cunningham3786@fhuux.com', '154 Blake Route', NULL, 'Denver', 'Il', '60647');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'Carl', 'Plant', '534-005-2708', 'Carl_Plant6899@iaart.org', '9945 Buttonwood Route', NULL, 'Philadelphia', 'Il', '60804');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'Hayden', 'Howard', '833-073-5683', 'Hayden_Howard8615@dbxli.site', '3180 Chart Street', NULL, 'Miami', 'Te', '60617');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (3, 'Enoch', 'Sylvester', '137-547-8368', 'Enoch_Sylvester3950@avn7d.video', '420 West Drive', NULL, 'Rochester', 'Mi', '60647');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'Nick', 'Stuart', '527-202-6821', 'Nick_Stuart3779@ds59r.media', '8948 Lincoln Tunnel', NULL, 'Laredo', 'Ka', '60804');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'Fred', 'Cunningham', '464-501-0316', 'Fred_Cunningham9620@nanoff.property', '8823 Victorian Avenue', NULL, 'Saint Paul', 'We', '60617');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'Marla', 'glass', '(703)-422-6118', 'Marla_Glass4471@nb44i.store', '1520 Birkenhead Way', NULL, 'New York', 'Il', '60435');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'Joyce', 'Paterson', '151-027-3720', 'Joyce_Paterson1795@ds59r.website', '3697 Howard Rue', NULL, 'Lyon', 'Ma', '60608');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'Nick', 'Lomax', '258-176-7811', 'Nick_Lomax7028@cke3u.biz', '7209 Besson Vale', NULL, 'Madison', 'Il', '60126');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (3, 'Marvin', 'Grady', '257-678-7256', 'Marvin_Grady9603@ckzyi.audio', '1768 Sherwood Vale', NULL, 'Paris', 'Il', '60625');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'Willow', 'Grey', '687-252-4052', 'Willow_Grey6856@dvqq2.digital', '2693 Eaglet Grove', NULL, 'Fayetteville', 'Il', '60617');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'Ellen', 'Campbell', '872-186-5318', 'Ellen_Campbell4526@dbxli.software', '1142 Magnolia Tunnel', NULL, 'Sacramento', 'Mi', '60647');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (3, 'Daron', 'Spencer', '665-540-4236', 'Daron_Spencer5612@cke3u.press', '2917 Thrale Grove', NULL, 'Hayward', 'Il', '60617');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'Christine', 'Heaton', '400-220-3688', 'Christine_Heaton6295@lyvnc.ca', '4311 Ashley Hill', NULL, 'Memphis', 'Oh', '60608');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'Daria', 'Brock', '306-006-1553', 'Daria_Brock9763@ptr6k.services', '4879 Westbourne Vale', NULL, 'London', 'Il', '60625');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (3, 'Maggie', 'Denton', '325-406-3062', 'Maggie_Denton227@y96lx.ca', '8097 Maple Lane', NULL, 'Amarillo', 'De', '60647');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'peter', 'Bell', '151-002-5338', 'Peter_Bell1052@p5emz.page', '3593 Ensign Alley', NULL, 'Venice', 'Il', '60804');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'Deborah', 'Butler', '731-518-8847', 'Deborah_Butler8654@xtwt3.online', '2909 Apsley Rue', NULL, 'Scottsdale', 'Ne', '60644');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (3, 'Grace', 'Logan', '200-060-5231', 'Grace_Logan2888@uagvw.software', '7398 Capeners Walk', NULL, 'Norfolk', 'Rh', '60608');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'Camila', 'Kennedy', '146-601-7767', 'Camila_Kennedy1370@fhuux.website', '631 Chester Avenue', NULL, 'Springfield', 'Mi', '60625');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'Joseph', 'Adams', '457-483-3380', 'Joseph_Adams7282@d9un8.info', '998 Norfolk Rue', NULL, 'Garland', 'De', '60647');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (3, 'Tom', 'Fowler', '475-171-4752', 'Tom_Fowler1715@chkzl.store', '8523 Heritage Street', NULL, 'Glendale', 'Oh', '60617');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'William', 'upton', '163-632-1875', 'William_Upton7703@jh02o.net', '3095 Champion Pass', NULL, 'Berna', 'Il', '60608');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'Allison', 'Roth', '148-406-4307', 'Allison_Roth4370@yafr7.host', '8309 Wager Drive', NULL, 'Otawa', 'Il', '60634');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'Carmella', 'ulyatt', '(858) 121-6105', 'Carmella_Ulyatt5985@p5emz.page', '5708 King Boulevard', NULL, 'Indianapolis', 'Il', '60623');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'Davina', 'Ross', '274-282-8078', 'Davina_Ross439@d9un8.store', '5135 Bocking Lane', NULL, 'Dallas', 'Il', '60085');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'Bree', 'Murray', '800-743-7278', 'Bree_Murray8696@p5emz.center', '6635 Bendall Walk', NULL, 'Bellevue', 'Il', '60014');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (3, 'Michaela', 'Hopkinson', '670-187-8627', 'Michaela_Hopkinson3145@mpibr.property', '4103 Caedmon Lane', NULL, 'Chicago', 'Il', '60647');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'Abdul', 'seymour', '283-466-3868', 'Abdul_Seymour195@ptr6k.org', '9335 Byland Rue', NULL, 'Madison', 'Il', '60617');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'Hayden', 'Warner', '357-476-3348', 'Hayden_Warner4866@ds59r.business', '763 Walnut Walk', NULL, 'Valetta', 'Or', '60608');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (3, 'Ada', 'Pierce', '856-736-4626', 'Ada_Pierce9868@zynuu.net', '1257 Rivervalley Vale', NULL, 'Seattle', 'Il', '60625');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'Isabel', 'Carter', '516-250-7376', 'Isabel_Carter6658@ptr6k.directory', '5815 Cardinal Way', NULL, 'Lisbon', 'Ne', '60647');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'Jolene', 'Townend', '200-783-8813', 'Jolene_Townend4723@1wa8o.zone', '1092 Canon Road', NULL, 'Saint Paul', 'Te', '60804');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (3, 'Daron', 'Dempsey', '864-868-5467', 'Daron_Dempsey3573@qu9ml.us', '7336 East Road', NULL, 'Omaha', 'Il', '60010');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'Anne', 'Evans', '887-458-6131', 'Anne_Evans161@voylg.digital', '6759 Andsell Vale', NULL, 'Long Beach', 'Il', '60608');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'Noah', 'Cooper', '611-462-8705', 'Noah_Cooper9626@bqkv0.works', '2053 Calverley Tunnel', NULL, 'Honolulu', 'Il', '60625');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (3, 'Sasha', 'Vangness', '648-200-1215', 'Sasha_Vangness5140@dvqq2.site', '4896 Besson Crossroad', NULL, 'Wien', 'Il', '60647');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'celina', 'Herbert', '(581) 4584053', 'Celina_Herbert1595@iscmr.tech', '5582 Ben Rue', NULL, 'Henderson', 'Il', '60617');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'Roger', 'Lunt', '283-535-5542', 'Roger_Lunt1228@xqj6f.info', '9587 Antrobus Rue', NULL, 'Rome', 'Il', '60608');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (3, 'Johnny', 'Swift', '652-566-2864', 'Johnny_Swift87@yafr7.name', '649 Abourne Road', NULL, 'Laredo', 'Lo', '60647');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'Manuel', 'Bryant', '472-181-5888', 'Manuel_Bryant6520@c2nyu.center', '5156 Longmoore Crossroad', NULL, 'San Francisco', 'Il', '60617');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'Hayden', 'Irving', '354-105-2414', 'Hayden_Irving2864@kyb7t.name', '5252 Mariner Hill', NULL, 'San Francisco', 'Mi', '60608');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'brad', 'Donnelly', '(884)-848-1678', 'Brad_Donnelly536@jh02o.info', '9561 Gautrey Walk', NULL, 'Paris', 'Il', '60625');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'Erin', 'Middleton', '768-745-8262', 'Erin_Middleton9879@urn0m.store', '9642 Heritage Tunnel', NULL, 'Scottsdale', 'Ne', '60647');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'Kenzie', 'Rose', '433-586-6304', 'Kenzie_Rose7135@yahoo.shop', '4806 Bethwin Road', NULL, 'Las Vegas', 'Il', '60804');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (3, 'Noah', 'Bradley', '160-886-4304', 'Noah_Bradley4144@nb44i.auction', '3113 Fairbairn Vale', NULL, 'Bridgeport', 'Ma', '60564');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'Liv', 'oliver', '232-887-7458', 'Liv_Oliver6647@xqj6f.space', '4914 Calshot Vale', NULL, 'Moreno Valley', 'Il', '60608');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'William', 'Parker', '514-305-0540', 'William_Parker3080@iscmr.host', '5369 Cavell Street', NULL, 'Dallas', 'Te', '60625');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (3, 'Rosalyn', 'Daniells', '403-418-8425', 'Rosalyn_Daniells9773@jh02o.business', '9476 Church Street', NULL, 'Fremont', 'Il', '60647');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'Judith', 'Mcgee', '738-625-4608', 'Judith_Mcgee4613@avn7d.design', '9223 Baltic Lane', NULL, 'Irving', 'Il', '60617');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'Angel', 'Pearce', '734-451-4384', 'Angel_Pearce3936@nb44i.works', '3854 English Way', NULL, 'Fremont', 'Wy', '60608');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (3, 'Harry', 'Williams', '250-403-3670', 'Harry_Williams3818@jcf8v.store', '2907 Vincent Hill', NULL, 'Richmond', 'Co', '60004');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'Penny', 'Rosenbloom', '857-705-1877', 'Penny_Rosenbloom7199@iaart.catering', '4961 Monroe Grove', NULL, 'Chicago', 'So', '60647');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'Hannah', 'Pearce', '223-684-4747', 'Hannah_Pearce2479@xtwt3.press', '442 Monroe Road', NULL, 'Salem', 'Co', '60617');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (3, 'Marvin', 'Woodley', '573-326-8228', 'Marvin_Woodley8228@urn0m.design', '9045 Cleveland Vale', NULL, 'Worcester', 'Il', '60608');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'Mary', 'Collis', '8158365786', 'Mary_Collis6789@nanoff.pro', '4776 Gautrey Vale', NULL, 'Seattle', 'Il', '60625');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'Matthew', 'Vass', '153-217-0667', 'Matthew_Vass7758@nmz0p.press', '5023 Chesterfield Route', NULL, 'Huntsville', 'Wa', '60647');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (3, 'Tom', 'Morgan', '527-830-0060', 'Tom_Morgan4068@jh02o.org', '4932 Bocking Rue', NULL, 'Miami', 'Wy', '60804');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'Brooklyn', 'Shelton', '234-325-3817', 'Brooklyn_Shelton5860@bqkv0.info', '5106 Bennett Pass', NULL, 'Laredo', 'Ne', '60440');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'Lauren', 'Mccormick', '772-551-6776', 'Lauren_Mccormick3123@cke3u.website', '7727 Caroline Tunnel', NULL, 'Orlando', 'Il', '60608');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (3, 'Marla', 'Ingham', '487-702-2865', 'Marla_Ingham7036@iaart.services', '1578 Carolina Way', NULL, 'Colorado Springs', 'Te', '60625');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'Julian', 'Knight', '235-217-6506', 'Julian_Knight292@avn7d.digital', '5619 Chambers Drive', NULL, 'Stockton', 'So', '60647');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'Marvin', 'Morris', '583-385-6087', 'Marvin_Morris6771@yfxpw.zone', '3858 Union Avenue', NULL, 'Phoenix', 'Il', '60617');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (3, 'Gil', 'Lomax', '217-165-5027', 'Gil_Lomax9867@yfxpw.website', '8566 Balham Way', NULL, 'Louisville', 'No', '60608');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'Jayden', 'Redwood', '280-083-7535', 'Jayden_Redwood327@y96lx.property', '1326 Rise Walk', NULL, 'Rome', 'Rh', '60804');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'Domenic', 'Tobin', '580-012-6235', 'Domenic_Tobin5724@d9un8.us', '9044 Lexington Vale', NULL, 'Bucharest', 'Te', '60617');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (3, 'Helen', 'Donnelly', '140-833-8077', 'Helen_Donnelly7022@lhp4j.mobi', '4539 Bayberry Tunnel', NULL, 'Orlando', 'Il', '60123');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'Barney', 'Kelly', '348-020-4011', 'Barney_Kelly1923@xtwt3.shop', '3014 Geffrye Grove', NULL, 'Las Vegas', 'Rh', '60608');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'Ethan', 'Thornton', '728-428-5304', 'Ethan_Thornton5454@cdpfn.site', '5661 Dutton Pass', NULL, 'Oakland', 'Il', '60506');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (3, 'Eileen', 'West', '256-887-0721', 'Eileen_West2168@cke3u.net', '9476 Byland Rue', NULL, 'Scottsdale', 'We', '60625');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'Jack', 'Warner', '504-206-7058', 'Jack_Warner8984@zynuu.audio', '6444 Cadogan Alley', NULL, 'Henderson', 'Te', '60637');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'Nicole', 'Hall', '336-868-2220', 'Nicole_Hall1401@ohqqh.business', '1493 Durnford Road', NULL, 'Otawa', 'Ma', '60647');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (3, 'Cassandra', 'Mooney', '556-383-2333', 'Cassandra_Mooney5542@bqkv0.store', '2080 Kingly Pass', NULL, 'El Paso', 'Ne', '60617');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'Peter', 'Collingwood', '745-570-5426', 'Peter_Collingwood2119@ohqqh.property', '1089 Bellenden Lane', NULL, 'Lincoln', 'Il', '60608');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'Boris', 'Pearson', '317-835-8657', 'Boris_Pearson7281@nb44i.press', '5770 Carol Pass', NULL, 'Louisville', 'Or', '60625');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'Ryan', 'stewart', '444-260-7863', 'Ryan_Stewart2887@dbxli.tech', '2982 Liverpool Route', NULL, 'Springfield', 'Il', '60647');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'Erick', 'Hale', '672-080-2513', 'Erick_Hale8444@lhp4j.app', '489 Canon Boulevard', NULL, 'Saint Paul', 'So', '60804');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'Joseph', 'Saunders', '730-264-1038', 'Joseph_Saunders58@voylg.catering', '5204 Linda Rue', NULL, 'Moreno Valley', 'Te', '60123');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (3, 'Helen', 'Jenkins', '708-671-0517', 'Helen_Jenkins3718@yafr7.net', '6716 Bellenden Crossroad', NULL, 'Washington', 'Il', '60608');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'marilyn', 'whitehouse', '873-507-5450', 'Marilyn_Whitehouse9127@yvu30.club', '1778 Chamberlain Rue', NULL, 'Louisville', 'Il', '60625');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (2, 'Anthony', 'Overson', '360-317-4312', 'Anthony_Overson9113@yfxpw.space', '8278 Central Hill', NULL, 'Richmond', 'Ka', '60647');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (3, 'Joseph', 'Emmott', '733-583-6547', 'Joseph_Emmott3281@v1wn5.design', '8359 Birkenhead Street', NULL, 'Miami', 'De', '60617');
INSERT INTO customers (status_id, first_name, last_name, phone, email_address, address_line_one, address_line_two, city, state, zip) VALUES (1, 'Rosalyn', 'Lynn', '(126)0362501', 'Rosalyn_Lynn5739@jcf8v.store', '3587 Lane Hill', NULL, 'Escondido', 'Il', '60608');